### ISSUE TITLE
store() on only defaults

### ISSUE THREAD

**Issue by JacobNeergaard** [TRP-Solutions/fancy-filter#6]
Only providing default doesn't save the filter. Future file doesn't get default (ufo calls).

Maybe kill $defaults.

Have more options
UNSET_MISSING (Already working), 
SET_ONLYKNOWN (Ufo call where GET in not complete - Avoid saving 'ufo'), 
SET_IFEMPTY (Defaults)

Maybe get() is not the right name for all this.

**Comment by Zatnosk** [comment]
```
$filter = FancyFilter::get('subscription');
$filter->set(['mycheck'=>$_GET['mycheck'],FancyFilter::SET_IFEMPTY);
```
